// S-2 견적 한/영 UI 사전 — jsx-easy-shift remember-quote/strings.ts 이식(문구 유지) + v2.0 확장.
// v2.0 조정: 다크 토글 문구 제거(앱 테마 단일), 스텝 5개 재정의(④확인·확정 ⑤행사 만들기 — §10 S-2),
// 목록·확정·핸드오프·403 문구 신설. 한/영 토글은 유지(§17.2).

const strings = {
  ko: {
    brandTag: "리멤버 MICE 솔루션",
    estTotal: "견적 합계",
    vatExcl: "VAT별도",
    steps: ["규모·유형", "베뉴", "옵션", "확인·확정", "행사 만들기"],
    // step1
    s1Title: "행사 규모·유형",
    projectName: "행사명(가칭)",
    projectPlaceholder: "예: 글로벌 테크 컨퍼런스",
    eventDateLabel: "행사 일자",
    eventEndDateLabel: "종료일 (당일 행사는 비움)",
    timeLabel: "운영 시간",
    natureLabel: "행사 성격",
    attendeeLabel: "총 참석인원 (패키지 볼륨 기준)",
    pax: "명",
    oversizeInline: (m: number) => `⚠️ ${m}명 초과 — 별도 협의 모드. 자동 견적은 제공되지 않으며, 영업 담당자와 별도 계약으로 진행됩니다.`,
    leadsCardTitle: "모객 솔루션",
    leadsCardBadge: "리멤버 차별화",
    leadsOn: "풀 패키지 (모객 포함)",
    leadsOnDesc: "리멤버 명함 데이터 기반 리드젠 · RSVP · 쇼업 게런티 포함",
    leadsOff: "순수 패키지 (모객 제외)",
    leadsOffDesc: "행사 구축·운영만 — 모객(리드) 비용 미포함",
    guaranteeLabel: "모객(게런티) 인원 (비용 산정 기준)",
    guaranteeNote: (min: number, max: number) => `※ 총 인원과 독립 · ${min}명~${max}명`,
    kpiLine: (ratio: number, ack: number) => `📊 모객 KPI: ${ratio}% 인정 · 실제 KPI 달성선 ${ack}명`,
    kpiZoneNote: (zone: number, g: number) => `(${zone}단계 · 게런티 ${g}명 기준)`,
    kpiUnderFloor: (min: number) => `게런티 ${min}명 미만 구간 — KPI 게이지 미적용 (KPI 최소 인정선 ${min}명 정책)`,
    targetingTitle: "타겟팅 5축",
    targetingDesc: "모객 리드젠의 타깃 조건 — 행사 생성 시 행사 설정 ①로 인계됩니다.",
    targetingAxes: ["기업 규모", "직급", "산업/업종", "직무", "근무 지역"],
    genTitle: "일반 참관객 관리",
    genBadge: "쇼업 게런티 아님",
    genDesc: "기고객·외부 등록자 등 일반 참관객 응대·관리 — 인당 20,000원 (모객 게런티와 독립).",
    genLabel: "일반 참관객 인원",
    genCalc: (n: number) => `${n}명 × 20,000원`,
    nextVenue: "다음: 베뉴 →",
    // step2
    s2Title: "베뉴 상세설정",
    s2Intro: "베뉴 DB에서 후보를 담거나 직접 입력해 여러 곳을 비교하고, 그중 1곳을 선택하세요 — 선택된 베뉴만 견적에 반영됩니다(택1).",
    dbTitle: "베뉴 DB에서 담기",
    dbFilterRegion: "지역",
    dbFilterAll: "전체",
    dbHallFit: { best: "적합", ok: "가능", large: "여유", small: "협소" } as Record<string, string>,
    dbAddBtn: "후보로 담기",
    dbNeedQuote: "별도 문의가",
    candidatesTitle: "베뉴 후보 (택1)",
    addVenue: "＋ 직접 입력 후보 추가",
    venueCardTitle: (i: number) => `베뉴 ${i}`,
    venueDateLabel: "행사 일자",
    removeVenue: "삭제",
    venueSelectedTag: "✓ 선택됨",
    venueSelectBtn: "이 베뉴 선택",
    venuesTotalLabel: "선택 베뉴 대관료 (택1)",
    autoCalcBtn: "↺ 인원 기준 자동 산정",
    hotelWarn: "본 호텔 비용은 예상 산정치이며, 확정 금액이 아닙니다. 실제 견적은 베뉴별 컨디션·일자·F&B 구성에 따라 달라지므로 반드시 베뉴 견적 확인 후 확정해야 합니다.",
    venueNameLabel: "베뉴명 (선택 입력)",
    venueNamePlaceholder: "예: 그랜드볼룸 (미정 시 비워두세요)",
    hallLabel: "홀 (선택 입력)",
    rentalLabel: "대관료 (자동 산정 · 수정 가능)",
    rentalCap: "※ 인원 변경 시 선택 베뉴만 자동 재계산됩니다. 직접 입력 시 그 값이 우선 사용됩니다.",
    fbNote: (v: string) => `🍽️ 호텔 F&B: 대관료의 80%(${v})까지 포함`,
    displayLabel: "디스플레이",
    displayLed: "LED", displayLedDesc: "대형 LED 패널",
    displayProjector: "빔프로젝터", displayProjectorDesc: "빔 + 스크린",
    ledNote: "💡 LED 디스플레이는 LED 오퍼레이팅(V-mix·엔지니어 · 250만원)이 필수로 자동 선택됩니다. 중계 비용은 포함되어 있지 않으며, LED만 쓰고 중계 없이 진행할 수도 있습니다.",
    prev: "← 이전", nextOption: "다음: 옵션 →",
    // step3
    s3Title: "추가 옵션",
    mediaPkg: "미디어 패키지", photowall: "포토월", pick1: "택 1",
    ledRequired: "LED 필수",
    ledOnlyTag: "LED 전용",
    boothStdTitle: "부스 설치 (일반형)", boothStdDesc: "조립식 부스 · 설치·철거 포함",
    boothPremTitle: "부스 설치 (고급형)", boothPremDesc: "목공·고급 마감 부스 · 설치·철거 포함",
    boothUnitLabel: "부스당 단가(원)",
    boothCountLabel: "부스 수 (0~50)",
    boothUnselected: "미선택",
    souvenirPriceLabel: "기념품 단가(원)",
    souvenirQtyLabel: "기념품 수량(개)",
    souvenirLinkNote: "※ 수량을 비우면 참석인원과 자동 연동됩니다",
    optSubtotal: "추가옵션 소계",
    reviewNext: "확인·확정 →",
    ledLockToast: "LED 디스플레이는 LED 오퍼레이팅(V-mix·엔지니어)이 필수입니다. 해제하려면 디스플레이를 빔프로젝터로 변경하세요.",
    onlineRelayOnToast: "온라인중계는 화면중계 시스템 위에 얹히는 구성이라 화면중계가 함께 적용됩니다 (합계 350만원).",
    screenRelayOffToast: "온라인중계가 선택되어 있어 화면중계는 해제할 수 없습니다. 온라인중계를 먼저 해제하세요.",
    recordingGateToast: "전체 녹화·편집은 중계 시스템이 있어야 합니다. 화면중계 또는 온라인중계를 먼저 선택하세요.",
    recordingAutoOffToast: "중계가 해제되어 전체 녹화·편집도 함께 해제되었습니다.",
    relayRequiredTag: "중계 필수",
    scalerAutoToast: "100명 이상은 LED 오퍼레이팅이 시스템에 자동 포함되어 별도 옵션 선택이 불필요합니다.",
    relayLockToast: "중계 옵션은 LED 디스플레이 선택 시에만 이용 가능합니다. 2단계(베뉴)에서 디스플레이를 LED로 변경하세요.",
    // step4
    s4Title: "견적 확인·확정",
    quoteTag: "견적서", defaultProject: "리멤버 MICE 견적",
    attendeeShort: (t: number) => `참석 ${t}명`,
    attendeeLeadShort: (t: number, g: number) => `참석 ${t}명 / 모객 ${g}명`,
    adjApplied: "· 조정 반영",
    l1: "1. 베뉴 사용료 [예상치 · 확정 아님]",
    l1warn: "⚠️ 호텔 비용은 예상 산정치이며, 반드시 베뉴 견적 확인을 통해 확정해야 합니다.",
    l2: "2. 시스템 구축", l3: "3. 디자인·브랜딩",
    l4: (t: number) => `4. 운영인력·등록·보험 (${t}명 기준)`,
    l5On: "5. PCO 기획료 (운영비+RSVP × 25%)",
    l5Off: "5. PCO 기획료 (운영비 × 25%)",
    l6: "6. 추가옵션 (별도)",
    l7: (g: number, hasOpt: boolean) => `${hasOpt ? "7" : "6"}. 모객 솔루션 [리드젠 · ${g}명]`,
    lGen: (no: number, n: number) => `${no}. 일반 참관객 관리 [${n}명 × 2만원]`,
    lTotal: "총 견적금액",
    vatLine: "VAT (10%)",
    totalInclVat: "합계 (VAT 포함)",
    adjTitle: "💰 금액 조정", adjSub: "(확정 전 세부 조정)",
    adjReset: "↺ 조정 초기화",
    adjDesc: "항목별로 할인(−)·추가(+) 금액을 입력하면 견적서에 '조정' 라인으로 반영되고, PCO 기획료·총액·VAT가 자동 재계산됩니다.",
    adjS1: "1. 베뉴 사용료", adjS2: "2. 시스템 구축", adjS3: "3. 디자인·브랜딩", adjS4: "4. 운영·등록·보험", adjOt: "추가옵션", adjLead: "모객 솔루션",
    adjAuto: "자동", adjSum: "조정 합계", adjPco: "PCO 기획료 재계산",
    clientInfoTitle: "고객·담당 정보",
    clientCompanyLabel: "고객사(주최)",
    contactNameLabel: "고객 담당자",
    contactEmailLabel: "고객 이메일",
    managerLabel: "담당 매니저",
    notesLabel: "비고 (참가 대상 등)",
    reviewNotice: "※ 본 견적은 참고용이며, 베뉴 컨디션에 따라 비용은 변동될 수 있습니다. 정확한 견적을 위해 1~2일 소요됩니다.",
    saveBtn: "💾 저장", saveNewVersionBtn: "💾 새 버전으로 저장", saving: "저장 중…",
    finalizeBtn: "이 버전으로 확정",
    finalizedBadge: "확정 · 잠김",
    lockedBanner: "확정된 견적입니다 — 저장하면 새 버전이 생성됩니다 (확정본은 잠금 유지).",
    supersededBanner: "새 버전이 있는 과거 버전입니다 — 최신 버전에서 수정하세요.",
    downloadBtn: "📊 견적서 다운로드 (Excel)",
    // step5 — 행사 만들기 (§16 핸드오프)
    s5Title: "이 견적으로 행사 만들기",
    s5Desc: "확정 견적의 행사 개요(행사명·일자·베뉴·인원·보장·타겟팅)가 새 행사에 프리필됩니다. 금액은 넘어가지 않으며, 프리필 값은 온보딩에서 수정할 수 있습니다.",
    s5NeedFinal: "확정 후 활성화됩니다 — ④에서 이 버전을 확정하세요.",
    s5CreateBtn: "이 견적으로 행사 만들기",
    s5Creating: "행사 생성 중…",
    s5LinkedTitle: "연결된 행사",
    s5GoProject: "연결된 행사로 이동 →",
    // 목록 (S-2 /quotes)
    listCaption: "준비 · S-2",
    listTitle: "견적",
    listNewQuote: "＋ 새 견적",
    listNewVersion: "＋ 새 버전",
    listDownload: "Excel 내려받기",
    listColVersion: "버전",
    listColHeadcount: "인원",
    listColVenue: "베뉴",
    listColLeads: "모객",
    listColTotal: "총액(VAT별도)",
    listColStatus: "상태",
    listLinkedGroup: (name: string) => `행사 연결 · ${name}`,
    listUnlinkedGroup: "견적만 있음 · 행사 미생성",
    listEmpty: "견적이 없습니다. 새 견적을 만들어 시작하세요.",
    listLeadsOn: "포함",
    listLeadsOff: "제외",
    statusLabels: { draft: "초안", proposed: "제안", accepted: "확정", archived: "보관", superseded: "구버전" } as Record<string, string>,
    summaryTitle: "선택 버전 요약",
    summaryEdit: "편집 (새 버전)",
    summaryEditDraft: "편집",
    forbiddenTitle: "접근 권한이 없습니다",
    forbiddenBody: "견적 메뉴는 영업·관리자 권한이 필요합니다.",
    tbd: "(미정)",
  },
  en: {
    brandTag: "Remember MICE Solution",
    estTotal: "Total",
    vatExcl: "VAT excl.",
    steps: ["Scale & Type", "Venue", "Options", "Review & Lock", "Create Event"],
    s1Title: "Event Scale & Type",
    projectName: "Event Name",
    projectPlaceholder: "e.g. Global Tech Conference",
    eventDateLabel: "Event Date",
    eventEndDateLabel: "End date (blank for one-day)",
    timeLabel: "Hours",
    natureLabel: "Event Nature",
    attendeeLabel: "Total Attendees (package volume)",
    pax: "pax",
    oversizeInline: (m: number) => `⚠️ Over ${m} pax — custom mode. No automatic quote; handled via a separate contract.`,
    leadsCardTitle: "Audience Recruitment",
    leadsCardBadge: "Remember exclusive",
    leadsOn: "Full Package (with recruitment)",
    leadsOnDesc: "Lead-gen powered by Remember's business-card data · RSVP · show-up guarantee",
    leadsOff: "Pure Package (no recruitment)",
    leadsOffDesc: "Event build & operations only — recruitment (lead) cost excluded",
    guaranteeLabel: "Guaranteed Attendees (billing basis)",
    guaranteeNote: (min: number, max: number) => `※ Independent of total attendees · ${min}–${max} pax`,
    kpiLine: (ratio: number, ack: number) => `📊 Recruitment KPI: ${ratio}% recognized · actual KPI threshold ${ack} pax`,
    kpiZoneNote: (zone: number, g: number) => `(tier ${zone} · based on ${g} pax guarantee)`,
    kpiUnderFloor: (min: number) => `Below ${min}-pax guarantee — KPI gauge not applied (floor: ${min} pax)`,
    targetingTitle: "Targeting (5 axes)",
    targetingDesc: "Lead-gen target filters — handed over to event settings ① when the event is created.",
    targetingAxes: ["Company size", "Title", "Industry", "Job function", "Region"],
    genTitle: "General Attendee Management",
    genBadge: "Not a show-up guarantee",
    genDesc: "Handling of general attendees (existing customers, external registrants) — KRW 20,000/pax, independent of the guarantee.",
    genLabel: "General attendees",
    genCalc: (n: number) => `${n} pax × KRW 20,000`,
    nextVenue: "Next: Venue →",
    s2Title: "Venue Details",
    s2Intro: "Add candidates from the venue DB or enter them directly, then pick exactly one — only the selected venue counts toward the quote.",
    dbTitle: "Add from Venue DB",
    dbFilterRegion: "Region",
    dbFilterAll: "All",
    dbHallFit: { best: "Best fit", ok: "OK", large: "Roomy", small: "Tight" } as Record<string, string>,
    dbAddBtn: "Add candidate",
    dbNeedQuote: "Quote on request",
    candidatesTitle: "Venue Candidates (pick 1)",
    addVenue: "＋ Add manual candidate",
    venueCardTitle: (i: number) => `Venue ${i}`,
    venueDateLabel: "Event Date",
    removeVenue: "Remove",
    venueSelectedTag: "✓ Selected",
    venueSelectBtn: "Select this venue",
    venuesTotalLabel: "Selected Venue Rental (pick 1)",
    autoCalcBtn: "↺ Auto-price by headcount",
    hotelWarn: "This hotel cost is an estimate, not a final amount. It must be confirmed against the venue's own quote.",
    venueNameLabel: "Venue Name (optional)",
    venueNamePlaceholder: "e.g. Grand Ballroom (leave blank if TBD)",
    hallLabel: "Hall (optional)",
    rentalLabel: "Rental (auto · editable)",
    rentalCap: "※ The selected venue reprices on headcount change. A manual value takes priority.",
    fbNote: (v: string) => `🍽️ Hotel F&B: up to 80% of rental (${v}) included`,
    displayLabel: "Display",
    displayLed: "LED", displayLedDesc: "Large LED panel",
    displayProjector: "Projector", displayProjectorDesc: "Beam + screen",
    ledNote: "💡 An LED display auto-includes LED Operating (V-mix + engineer, KRW 2,500,000). Relay cost is NOT part of it — you can run LED with no relay at all.",
    prev: "← Back", nextOption: "Next: Options →",
    s3Title: "Add-ons",
    mediaPkg: "Media Package", photowall: "Photo Wall", pick1: "Pick 1",
    ledRequired: "LED required",
    ledOnlyTag: "LED only",
    boothStdTitle: "Booth (Standard)", boothStdDesc: "Modular booth · install/removal incl.",
    boothPremTitle: "Booth (Premium)", boothPremDesc: "Carpentry-built, premium finish · install/removal incl.",
    boothUnitLabel: "Unit price per booth (KRW)",
    boothCountLabel: "Booths (0–50)",
    boothUnselected: "None",
    souvenirPriceLabel: "Souvenir unit price (KRW)",
    souvenirQtyLabel: "Souvenir quantity",
    souvenirLinkNote: "※ Leave quantity blank to auto-link to headcount",
    optSubtotal: "Add-ons Subtotal",
    reviewNext: "Review & Lock →",
    ledLockToast: "An LED display requires LED Operating (V-mix + engineer). Switch the display to Projector to remove it.",
    onlineRelayOnToast: "Online Relay builds on the Live Screen Relay system, so Live Screen Relay is applied together (KRW 3,500,000 total).",
    screenRelayOffToast: "Live Screen Relay cannot be removed while Online Relay is selected. Remove Online Relay first.",
    recordingGateToast: "Full Recording & Edit needs a relay system. Select Live Screen Relay or Online Relay first.",
    recordingAutoOffToast: "Relay was removed, so Full Recording & Edit was removed as well.",
    relayRequiredTag: "Relay required",
    scalerAutoToast: "For 100+ pax, LED Operating is auto-included in the system — no separate option needed.",
    relayLockToast: "Live screen relay is available only with an LED display. Switch the display to LED in step 2 (Venue).",
    s4Title: "Review & Lock",
    quoteTag: "ESTIMATE", defaultProject: "Remember MICE Estimate",
    attendeeShort: (t: number) => `${t} pax`,
    attendeeLeadShort: (t: number, g: number) => `${t} pax / ${g} pax guaranteed`,
    adjApplied: "· adjusted",
    l1: "1. Venue Rental [Estimate · Not Final]",
    l1warn: "⚠️ Hotel cost is an estimate; it must be confirmed against the venue's own quote.",
    l2: "2. System / AV", l3: "3. Design / Branding",
    l4: (t: number) => `4. Operations · Staff · Insurance (${t} pax)`,
    l5On: "5. PCO Fee (operating cost + RSVP × 25%)",
    l5Off: "5. PCO Fee (operating cost × 25%)",
    l6: "6. Add-ons (separate)",
    l7: (g: number, hasOpt: boolean) => `${hasOpt ? "7" : "6"}. Audience Recruitment [lead-gen · ${g} pax]`,
    lGen: (no: number, n: number) => `${no}. General Attendee Management [${n} pax × KRW 20,000]`,
    lTotal: "Grand Total",
    vatLine: "VAT (10%)",
    totalInclVat: "Total (VAT incl.)",
    adjTitle: "💰 Adjust Amounts", adjSub: "(fine-tune before locking)",
    adjReset: "↺ Reset",
    adjDesc: "Enter a discount (−) or addition (+) per line; the PCO fee, total and VAT recalculate automatically.",
    adjS1: "1. Venue Rental", adjS2: "2. System / AV", adjS3: "3. Design / Branding", adjS4: "4. Ops / Reg / Insurance", adjOt: "Add-ons", adjLead: "Audience Recruitment",
    adjAuto: "Auto", adjSum: "Adjustment total", adjPco: "PCO fee recalculated",
    clientInfoTitle: "Client & Manager",
    clientCompanyLabel: "Client (Organizer)",
    contactNameLabel: "Client Contact",
    contactEmailLabel: "Client Email",
    managerLabel: "Account Manager",
    notesLabel: "Notes (audience, etc.)",
    reviewNotice: "* This quote is for reference; cost may vary by venue conditions. A finalized quote takes 1–2 business days.",
    saveBtn: "💾 Save", saveNewVersionBtn: "💾 Save as new version", saving: "Saving…",
    finalizeBtn: "Lock this version",
    finalizedBadge: "Final · Locked",
    lockedBanner: "This quote is locked — saving creates a new version (the final stays locked).",
    supersededBanner: "This is an old version with a newer one — edit the latest version.",
    downloadBtn: "📊 Download Estimate (Excel)",
    s5Title: "Create an Event from this Quote",
    s5Desc: "The finalized quote's overview (name, date, venue, headcount, guarantee, targeting) prefills the new event. No amounts are handed over; prefilled values are editable in onboarding.",
    s5NeedFinal: "Enabled after locking — lock this version in step 4.",
    s5CreateBtn: "Create event from this quote",
    s5Creating: "Creating event…",
    s5LinkedTitle: "Linked event",
    s5GoProject: "Go to the linked event →",
    listCaption: "PREP · S-2",
    listTitle: "Quotes",
    listNewQuote: "＋ New Quote",
    listNewVersion: "＋ New Version",
    listDownload: "Download Excel",
    listColVersion: "Ver.",
    listColHeadcount: "Pax",
    listColVenue: "Venue",
    listColLeads: "Leads",
    listColTotal: "Total (VAT excl.)",
    listColStatus: "Status",
    listLinkedGroup: (name: string) => `Linked event · ${name}`,
    listUnlinkedGroup: "Quote only · no event yet",
    listEmpty: "No quotes yet. Create one to get started.",
    listLeadsOn: "Incl.",
    listLeadsOff: "Excl.",
    statusLabels: { draft: "Draft", proposed: "Proposed", accepted: "Final", archived: "Archived", superseded: "Superseded" } as Record<string, string>,
    summaryTitle: "Selected Version",
    summaryEdit: "Edit (new version)",
    summaryEditDraft: "Edit",
    forbiddenTitle: "Access denied",
    forbiddenBody: "The quotes menu requires a sales or admin role.",
    tbd: "(TBD)",
  },
};

export type QuoteLang = keyof typeof strings;
export type QuoteStrings = (typeof strings)["ko"];
export default strings;
