// Auto-generated by venue_pipeline.py — DO NOT EDIT MANUALLY.
// Generated: 2026-04-10 16:40
// Schema version: 1.0.0
//
// v2.0 이식 (설계서 §17.1): jsx-easy-shift main 6047834 src/lib/venuedb.js.
// 값·헬퍼 로직 불변, TS 타입만 부여. 단 reference_cases·source_files 필드는 전량 제거
// (#RULE-NO-COMPANY — 실고객사명·실거래액. 설계서 §12·§17.1). 20곳·halls·pricing·
// extraction_confidence·missing_fields·last_updated는 그대로 유지.

export type TrustLevel = 'verified' | 'quote' | 'inquiry'

export interface VenueHall {
  name: string
  capacity: Record<string, number | null>
  area_m2: number | null
  ceiling_height_m?: number | null
  divisible?: boolean | null
  [key: string]: unknown
}

export interface VenueRecord {
  id: string
  name: string
  grade: string
  region: string
  address?: string | null
  halls: VenueHall[]
  pricing: {
    base_rental_krw: number | null
    rental_range?: { min: number | null; max: number | null; median: number | null } | null
    service_charge_pct?: number | null
    vat_included?: boolean | null
    price_notes?: string | null
    [key: string]: unknown
  }
  features?: Record<string, unknown> | null
  extraction_confidence?: string
  missing_fields?: string[]
  last_updated?: string
  [key: string]: unknown
}

export type VenueWithTrust = VenueRecord & { trust: TrustLevel }

export interface ScaledHall extends VenueHall {
  scaledPrice: number | null
  fit: 'best' | 'ok' | 'large' | 'small'
}

export const VENUE_DB: Record<string, VenueRecord> = {
  "andaz_gangnam": {
    "id": "andaz_gangnam",
    "name": "안다즈 서울 강남",
    "grade": "5star",
    "region": "서울 강남",
    "address": "서울시 강남구 논현로 854 06022",
    "halls": [
      {
        "name": "Studio 3",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 8000000,
      "rental_range": {
        "min": 8000000,
        "max": 8000000,
        "median": 8000000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": true,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 1개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": true,
      "av_rental_notes": "프로젝터 스크린 550,000 1 1 무료 제공 프로젝터 당 / 프로젝터 & 스크린",
      "parking": null,
      "restrictions": [
        "반입 및 내부 반출이 엄격히 제한"
      ],
      "amenities": [
        "AV 기본 제공",
        "AV 상세: 프로젝터 스크린 550,000 1 1 무료 제공 프로젝터 당 / 프로젝터 & 스크린",
        "제한: 반입 및 내부 반출이 엄격히 제한"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "banyan_tree_seoul": {
    "id": "banyan_tree_seoul",
    "name": "반얀트리 서울",
    "grade": "5star",
    "region": "서울 강북",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": null
    },
    "features": {
      "av_included": null,
      "av_rental_notes": "LED",
      "parking": null,
      "restrictions": [],
      "amenities": [
        "AV 상세: LED"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "low",
    "missing_fields": [
      "address",
      "halls",
      "base_rental_krw",
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "conrad_seoul": {
    "id": "conrad_seoul",
    "name": "콘래드 서울",
    "grade": "5star",
    "region": "서울 강남",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": 7680000,
      "rental_range": {
        "min": 7680000,
        "max": 7680000,
        "median": 7680000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 1개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": false,
      "av_rental_notes": "LED 1 KRW 2,500,000 KRW 2,500,000 9m x 3.5m",
      "parking": null,
      "restrictions": [],
      "amenities": [
        "AV 별도 렌탈",
        "AV 상세: LED 1 KRW 2,500,000 KRW 2,500,000 9m x 3.5m"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "medium",
    "missing_fields": [
      "address",
      "halls",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "fairmont_ambassador_seoul": {
    "id": "fairmont_ambassador_seoul",
    "name": "페어몬트 앰배서더 서울",
    "grade": "5star",
    "region": "서울 강남",
    "address": null,
    "halls": [
      {
        "name": "그랜드볼룸",
        "capacity": {
          "theater": 500,
          "banquet": 360,
          "classroom": 360,
          "reception": null
        },
        "area_m2": 675,
        "ceiling_height_m": null,
        "divisible": true,
        "note": "지하 1층 · 3섹션 분할 가능 · 10.5×4m LED 월 · U-Shape 120석"
      },
      {
        "name": "갤러리 7",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null,
        "note": "소규모 비즈니스 미팅 · 스몰 웨딩 전용"
      },
      {
        "name": "AZALEAS",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 27500000,
      "rental_range": {
        "min": 7000000,
        "max": 48000000,
        "median": 27500000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 2개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": "주차 - 무료 제공 Valet Parking - 40,000원 (3",
      "restrictions": [],
      "amenities": [
        "주차: 주차 - 무료 제공 Valet Parking - 40,000원 (3"
      ]
    },
    "target_events": [
      "IR",
      "conference",
      "seminar"
    ],
    "recommended_tier": [
      "Standard",
      "Premium"
    ],
    "description": "2021.02 개관 · 여의도 Parc1 · 더현대 서울 연결 · 아코르 계열 · Standard/Premium 최적 · 리처드 로저스 설계",
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address",
      "av_included"
    ],
    "last_updated": "2026-04-10"
  },
  "four_seasons_seoul": {
    "id": "four_seasons_seoul",
    "name": "포시즌스 호텔 서울",
    "grade": "5star",
    "region": "서울 강북",
    "address": null,
    "halls": [
      {
        "name": "GARAM",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Garam",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 6940000,
      "rental_range": {
        "min": 6940000,
        "max": 6940000,
        "median": 6940000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 1개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": null,
      "restrictions": [],
      "amenities": []
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address",
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "grand_intercontinental_parnas": {
    "id": "grand_intercontinental_parnas",
    "name": "그랜드 인터컨티넨탈 서울 파르나스",
    "grade": "5star",
    "region": "서울 강남",
    "address": "서울시 강남구 521 테헤란로, 135-732",
    "halls": [
      {
        "name": "그랜드볼룸",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 7863636,
      "rental_range": {
        "min": 6500000,
        "max": 22000000,
        "median": 7863636
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 3건에서 대관료 키워드 근처 7개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": "Parking Ticket W9,000/hour 무료 제공",
      "restrictions": [],
      "amenities": [
        "주차: Parking Ticket W9,000/hour 무료 제공"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "av_included"
    ],
    "last_updated": "2026-04-10"
  },
  "gs_amoris_hall": {
    "id": "gs_amoris_hall",
    "name": "GS아모리스홀",
    "grade": "unique",
    "region": "서울 강남",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": null
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": null,
      "restrictions": [],
      "amenities": []
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "low",
    "missing_fields": [
      "address",
      "halls",
      "base_rental_krw",
      "av_included",
      "parking",
      "jpg_ocr_required"
    ],
    "last_updated": "2026-04-10"
  },
  "hotel_naru_mgallery": {
    "id": "hotel_naru_mgallery",
    "name": "호텔나루 서울 엠갤러리",
    "grade": "4star",
    "region": "서울 강남",
    "address": null,
    "halls": [
      {
        "name": "GALLERY",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 1",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 1+2",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 110",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 12",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 13",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 14",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 15",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 16",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 17",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 18",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 2",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 20",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 23",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 24",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 25",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 26",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 27",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 28",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 29",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 3",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 3+4",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 30",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 31",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 32",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 37",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 38",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 39",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 4",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 40",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 41",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 42",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 43",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 44",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 45",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 6",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 60",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 7",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Gallery 800",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "갤러리 3+4",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 9350000,
      "rental_range": {
        "min": 7700000,
        "max": 11000000,
        "median": 9350000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 3건에서 대관료 키워드 근처 6개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": true,
      "av_rental_notes": "빔프로젝터 & 스크린 1 1 550,000 호텔무료제공 * 5,200 ANSI / 120\" (16:9) - 갤러리 3+4",
      "parking": "주차요금에 발렛 서비스가 포함되어있습니다.",
      "restrictions": [],
      "amenities": [
        "주차: 주차요금에 발렛 서비스가 포함되어있습니다.",
        "AV 기본 제공",
        "AV 상세: 빔프로젝터 & 스크린 1 1 550,000 호텔무료제공 * 5,200 ANSI / 120\" (16:9) - 갤러리 3+4"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address"
    ],
    "last_updated": "2026-04-10"
  },
  "hotel_shilla_seoul": {
    "id": "hotel_shilla_seoul",
    "name": "호텔 신라 서울",
    "grade": "5star",
    "region": "서울 강북",
    "address": "서울시 중구 동호로 249 고객서명란",
    "halls": [
      {
        "name": "영빈관",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null,
        "name_en": "YEONGBINGWAN"
      }
    ],
    "pricing": {
      "base_rental_krw": 15000000,
      "rental_range": {
        "min": 10000000,
        "max": 20000000,
        "median": 15000000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 2개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": "프로젝터 (6,500 ansi) 3 00,000 1 3 00,000",
      "parking": null,
      "restrictions": [],
      "amenities": [
        "AV 상세: 프로젝터 (6,500 ansi) 3 00,000 1 3 00,000"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "josun_palace_gangnam": {
    "id": "josun_palace_gangnam",
    "name": "조선 팰리스 서울 강남",
    "grade": "5star",
    "region": "서울 강남",
    "address": null,
    "halls": [
      {
        "name": "ROYAL CHAMBER",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": 240,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Royal Chamber",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": 240,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Royal Chamber 1",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Royal Chamber 4",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Royal Chamber 9",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 8450000,
      "rental_range": {
        "min": 6800000,
        "max": 14500000,
        "median": 8450000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": true,
      "price_notes": "견적서 2건에서 대관료 키워드 근처 6개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": "LED 1 ,100,000 1,100,000 1 1,100,000 -빔 프로젝터 미사용시 대관료로 대체",
      "parking": "Parking - - - Complimentary 주차 무료제공",
      "restrictions": [],
      "amenities": [
        "주차: Parking - - - Complimentary 주차 무료제공",
        "AV 상세: LED 1 ,100,000 1,100,000 1 1,100,000 -빔 프로젝터 미사용시 대관료로 대체"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address",
      "av_included"
    ],
    "last_updated": "2026-04-10"
  },
  "jw_marriott_seoul": {
    "id": "jw_marriott_seoul",
    "name": "JW메리어트 서울",
    "grade": "5star",
    "region": "서울 강남",
    "address": "서울특별시 서초구 신반포로 176 (반포동 19-3번지), 06546",
    "halls": [
      {
        "name": "Salon 1",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Salon 2",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Salon 3",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Salon 4",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Salon 4+5",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "Salon 5",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "포디움",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 8800000,
      "rental_range": {
        "min": 8800000,
        "max": 8800000,
        "median": 8800000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": "offset",
        "ratio": 1,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": "대관료 전액 F&B로 상쇄 가능 (주류 별도)"
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "씨랩 견적서에서 Salon 대관료 정상가 W8,800,000 확인 (F&B 상쇄로 무료제공)"
    },
    "features": {
      "av_included": true,
      "av_rental_notes": "LCD 프로젝터 (빌트인) 무료, 유/무선 마이크 무료, 스크린/데이터케이블 무료",
      "parking": "무료제공",
      "restrictions": [],
      "amenities": [
        "주차: 무료제공",
        "AV 기본 제공",
        "AV 상세: LCD 프로젝터 (빌트인) 무료, 유/무선 마이크 무료, 스크린/데이터케이블 무료"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [],
    "last_updated": "2026-04-10"
  },
  "le_meridien_moxy_myeongdong": {
    "id": "le_meridien_moxy_myeongdong",
    "name": "르메르디앙 목시 서울 명동",
    "grade": "4star",
    "region": "서울 강북",
    "address": null,
    "halls": [
      {
        "name": "포디움",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 4000000,
      "rental_range": {
        "min": 4000000,
        "max": 4000000,
        "median": 4000000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 1건에서 대관료 키워드 근처 1개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": "주차\n주차비 1 1 2 5,000 무료제공 무료제공 *발렛파킹 시, 보증인원의 50%까지 무",
      "restrictions": [],
      "amenities": [
        "주차: 주차\n주차비 1 1 2 5,000 무료제공 무료제공 *발렛파킹 시, 보증인원의 50%까지 무"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address",
      "av_included"
    ],
    "last_updated": "2026-04-10"
  },
  "lotte_hotel_seoul": {
    "id": "lotte_hotel_seoul",
    "name": "롯데호텔 서울",
    "grade": "5star",
    "region": "서울 강북",
    "address": "서울특별시 중구 을지로30(소공동) 주소 :",
    "halls": [
      {
        "name": "벨뷰 스위트",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      },
      {
        "name": "포디움",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 6500000,
      "rental_range": {
        "min": 6500000,
        "max": 6500000,
        "median": 6500000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 2건에서 대관료 키워드 근처 2개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": "주차권 - - Complimentary Free Of Charge",
      "restrictions": [],
      "amenities": [
        "주차: 주차권 - - Complimentary Free Of Charge"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "av_included"
    ],
    "last_updated": "2026-04-10"
  },
  "novotel_ambassador_gangnam": {
    "id": "novotel_ambassador_gangnam",
    "name": "노보텔 앰배서더 서울 강남",
    "grade": "4star",
    "region": "서울 강남",
    "address": null,
    "halls": [
      {
        "name": "알자스 프로방스",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": 185,
        "ceiling_height_m": 11,
        "divisible": null,
        "name_en": "Alsace Provence"
      }
    ],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 2건에서 대관료/대실료 키워드를 찾지 못함"
    },
    "features": {
      "av_included": true,
      "av_rental_notes": "빔 am 프 p 로 ro 젝 je 터 ctor 1EA ₩330,000 100.0% 무료제공 *스크린 사이즈 : 가로 세로 4m*3.3m",
      "parking": "Parking 무료주차 ₩33,000 100.0% 무료제공 *행사 참석",
      "restrictions": [],
      "amenities": [
        "주차: Parking 무료주차 ₩33,000 100.0% 무료제공 *행사 참석",
        "AV 기본 제공",
        "AV 상세: 빔 am 프 p 로 ro 젝 je 터 ctor 1EA ₩330,000 100.0% 무료제공 *스크린 사이즈 : 가로 세로 4m*3.3m"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "medium",
    "missing_fields": [
      "address",
      "base_rental_krw",
      "rental_keyword_not_found"
    ],
    "last_updated": "2026-04-10"
  },
  "oakwood_premier_coex": {
    "id": "oakwood_premier_coex",
    "name": "오크우드 프리미어 코엑스센터",
    "grade": "4star",
    "region": "서울 강남",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": 6400000,
      "rental_range": {
        "min": 4700000,
        "max": 8100000,
        "median": 6400000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "xls 견적서에서 대관료 4개 추출"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": "빔 프로젝트 : 정면, 우측 총 2개 가능 L",
      "parking": null,
      "restrictions": [],
      "amenities": [
        "AV 상세: 빔 프로젝트 : 정면, 우측 총 2개 가능 L"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "address",
      "halls"
    ],
    "last_updated": "2026-04-10"
  },
  "park_hyatt_seoul": {
    "id": "park_hyatt_seoul",
    "name": "파크하얏트 서울",
    "grade": "5star",
    "region": "서울 강남",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": true,
      "price_notes": "견적서 1건에서 대관료/대실료 키워드를 찾지 못함"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": null,
      "restrictions": [],
      "amenities": []
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "low",
    "missing_fields": [
      "address",
      "halls",
      "base_rental_krw",
      "rental_keyword_not_found",
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "pie_factory": {
    "id": "pie_factory",
    "name": "파이팩토리",
    "grade": "unique",
    "region": "서울 강남",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": null
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": null,
      "restrictions": [],
      "amenities": []
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "low",
    "missing_fields": [
      "address",
      "halls",
      "base_rental_krw",
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "sofitel_ambassador_seoul": {
    "id": "sofitel_ambassador_seoul",
    "name": "소피텔 앰배서더 서울",
    "grade": "5star",
    "region": "서울 강남",
    "address": null,
    "halls": [
      {
        "name": "그랜드 볼룸 방돔",
        "capacity": {
          "theater": null,
          "banquet": 300,
          "classroom": null,
          "reception": 600
        },
        "area_m2": 587,
        "ceiling_height_m": 5.5,
        "divisible": true,
        "note": "17×33.6m · 3섹션 분할 · 초대형 빌트인 미디어월(12.5×4.3m) + 측면 서브 미디어월 2개(각 3.9×2.7m) · 1Gbps 초고속 인터넷 · 엘리베이터/에스컬레이터 동선"
      },
      {
        "name": "바스티유 룸",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": true,
        "note": "중연회장 · 3섹션 분할 · 석촌호수뷰 자연채광"
      },
      {
        "name": "콩코드 룸",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null,
        "note": "소연회장 · VIP/프라이빗 · 가든뷰 자연채광"
      },
      {
        "name": "포디움",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": null,
        "ceiling_height_m": null,
        "divisible": null,
        "note": "소규모 · 기획자 노트: UI 기준 '작음' 분류"
      }
    ],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": true,
      "price_notes": "견적서 3건에서 대관료/대실료 키워드를 찾지 못함"
    },
    "features": {
      "av_included": true,
      "av_rental_notes": "LED 3660mm X 2058.7mm / Pixel pitch 1.9mm",
      "parking": null,
      "restrictions": [],
      "amenities": [
        "AV 기본 제공",
        "AV 상세: LED 3660mm X 2058.7mm / Pixel pitch 1.9mm"
      ]
    },
    "target_events": [
      "conference",
      "seminar",
      "banquet"
    ],
    "recommended_tier": [
      "Premium",
      "Grand"
    ],
    "description": "2021.09 개관 · 잠실 · KT 송파지사 부지 · 한국 첫 소피텔 · 석촌호수뷰 · 아태 최초 소피텔 호텔&레지던스 · Premium(100~200명) 최적 · Grand(200+) 경계선",
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "medium",
    "missing_fields": [
      "address",
      "base_rental_krw",
      "rental_keyword_not_found",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "the_plaza": {
    "id": "the_plaza",
    "name": "더플라자",
    "grade": "5star",
    "region": "서울 강북",
    "address": null,
    "halls": [],
    "pricing": {
      "base_rental_krw": null,
      "rental_range": {
        "min": null,
        "max": null,
        "median": null
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": null
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": null,
      "restrictions": [],
      "amenities": []
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "low",
    "missing_fields": [
      "address",
      "halls",
      "base_rental_krw",
      "av_included",
      "parking"
    ],
    "last_updated": "2026-04-10"
  },
  "westin_parnas": {
    "id": "westin_parnas",
    "name": "웨스틴 서울 파르나스",
    "grade": "5star",
    "region": "서울 강남",
    "address": "서울특별시 강남구 봉은사로 524 웨스틴 서울 파르나스",
    "halls": [
      {
        "name": "아틀라스홀",
        "capacity": {
          "theater": null,
          "banquet": null,
          "classroom": null,
          "reception": null
        },
        "area_m2": 363,
        "ceiling_height_m": null,
        "divisible": null
      }
    ],
    "pricing": {
      "base_rental_krw": 19750000,
      "rental_range": {
        "min": 11000000,
        "max": 33000000,
        "median": 19750000
      },
      "rental_by_session": {
        "half_day": null,
        "full_day": null,
        "evening": null
      },
      "fnb_policy": {
        "type": null,
        "ratio": null,
        "min_guarantee_krw": null,
        "min_pax": null,
        "notes": null
      },
      "service_charge_pct": 0.1,
      "vat_included": false,
      "price_notes": "견적서 2건에서 대관료 키워드 근처 4개 추출, 중앙값 사용"
    },
    "features": {
      "av_included": null,
      "av_rental_notes": null,
      "parking": "주차권 W10,000/hour 무료제공",
      "restrictions": [],
      "amenities": [
        "주차: 주차권 W10,000/hour 무료제공"
      ]
    },
    "target_events": [],
    "recommended_tier": [],
    "description": null,
    "strengths": [],
    "weaknesses": [],
    "extraction_confidence": "high",
    "missing_fields": [
      "av_included"
    ],
    "last_updated": "2026-04-10"
  }
};

/** 등급별 베뉴 목록 */
export const getVenuesByGrade = (grade: string): VenueRecord[] =>
  Object.values(VENUE_DB).filter((v) => v.grade === grade);

/** 지역별 베뉴 목록 */
export const getVenuesByRegion = (region: string): VenueRecord[] =>
  Object.values(VENUE_DB).filter((v) => v.region === region);

/** ID로 베뉴 조회 */
export const getVenueById = (id: string): VenueRecord | null => VENUE_DB[id] || null;

/** 대관료가 확인된 베뉴만 */
export const getVenuesWithPrice = (): VenueRecord[] =>
  Object.values(VENUE_DB).filter((v) => v.pricing?.base_rental_krw != null);

/** 대관료 미확인 (별도 문의 필요) 베뉴만 */
export const getVenuesNeedQuote = (): VenueRecord[] =>
  Object.values(VENUE_DB).filter((v) => v.pricing?.base_rental_krw == null);

// ============================================================
// Phase 6 확장 helper (기획자 커스텀)
// ============================================================

const TRUST_MAP: Record<string, TrustLevel> = {
  // Verified (12) - 레퍼런스 + 가격 확보
  jw_marriott_seoul: "verified",
  grand_intercontinental_parnas: "verified",
  lotte_hotel_seoul: "verified",
  le_meridien_moxy_myeongdong: "verified",
  andaz_gangnam: "verified",
  oakwood_premier_coex: "verified",
  westin_parnas: "verified",
  josun_palace_gangnam: "verified",
  fairmont_ambassador_seoul: "verified",
  four_seasons_seoul: "verified",
  hotel_shilla_seoul: "verified",
  hotel_naru_mgallery: "verified",
  // Quote (3) - 레퍼런스만, 가격 별도문의
  novotel_ambassador_gangnam: "quote",
  sofitel_ambassador_seoul: "quote",
  conrad_seoul: "quote",
  // Inquiry (5) - 자료 부족
  gs_amoris_hall: "inquiry",
  the_plaza: "inquiry",
  banyan_tree_seoul: "inquiry",
  pie_factory: "inquiry",
  park_hyatt_seoul: "inquiry",
};

export function getTrustLevel(venueId: string): TrustLevel {
  return TRUST_MAP[venueId] || "inquiry";
}

export function getAllVenues(): VenueWithTrust[] {
  return Object.entries(VENUE_DB).map(([id, v]) => ({
    ...v,
    id,
    trust: getTrustLevel(id),
  }));
}

export function filterVenues({ region = null, grade = null, trust = null }: { region?: string | null; grade?: string | null; trust?: TrustLevel | null } = {}): VenueWithTrust[] {
  return getAllVenues().filter((v) => {
    if (region && v.region !== region) return false;
    if (grade && v.grade !== grade) return false;
    if (trust && v.trust !== trust) return false;
    return true;
  });
}

// B안 포맷: "Verified · 시장가 대비 ±23%"
export function getTrustBadge(venue: VenueWithTrust): string {
  const trust = venue.trust || getTrustLevel(venue.id);
  const labels: Record<TrustLevel, string> = { verified: "Verified", quote: "Quote", inquiry: "Inquiry" };
  const label = labels[trust];
  const r = venue.pricing?.rental_range;
  if (trust === "verified" && r?.median && r.min && r.max) {
    const dev = Math.round(((r.max - r.min) / r.median) * 50);
    return dev > 0 ? `${label} · 시장가 대비 ±${dev}%` : `${label} · 단일 레퍼런스`;
  }
  if (trust === "quote") return `${label} · 별도 문의가`;
  return `${label} · 자료 확보 필요`;
}

export function getConfidenceLine(venueId: string): string {
  const v = VENUE_DB[venueId];
  if (!v) return "";
  return getTrustBadge({ ...v, id: venueId, trust: getTrustLevel(venueId) });
}

export function getVenueRental(venueId: string): number | null {
  return VENUE_DB[venueId]?.pricing?.base_rental_krw ?? null;
}

export const ACTIVE_REGIONS = ["서울 강남", "서울 강북"];
export const GRADE_LABELS: Record<string, string> = {
  "5star": "5성급 호텔",
  "4star": "4성급 호텔",
  unique: "유니크 베뉴",
};

export function getScaledHalls(venueId: string, targetHeadcount: number): ScaledHall[] {
  const v = VENUE_DB[venueId];
  if (!v) return [];
  const base = v.pricing?.base_rental_krw;
  const halls = (v.halls && v.halls.length > 0) 
    ? v.halls 
    : [{ name: "메인홀", capacity: {}, area_m2: null }];

  // base_rental을 "100명 기준가"로 간주
  // 스케일 공식: ratio = (target / 100) ^ 0.6  (체감형 곡선)
  const HEADCOUNT_BASE = 100;
  const ratio = base ? Math.pow(targetHeadcount / HEADCOUNT_BASE, 0.6) : 1;
  const venueScaledBase = base ? Math.round((base * ratio) / 100000) * 100000 : null;

  // 홀별 변동: 순서대로 0.85x, 1.0x, 1.15x, 1.3x, 1.45x (메인홀일수록 비쌈)
  const hallMultipliers = [1.3, 1.0, 0.85, 1.15, 1.45, 0.7, 1.6, 0.6, 1.7, 0.5];

  return halls.slice(0, 10).map((h: VenueHall, idx: number) => {
    const mult = hallMultipliers[idx] ?? 1.0;
    const scaledPrice = venueScaledBase 
      ? Math.round((venueScaledBase * mult) / 100000) * 100000 
      : null;

    // 적합도: 첫 번째 홀(가장 큰 메인홀)을 인원이 많을수록 추천
    let fit: ScaledHall["fit"] = "ok";
    if (idx === 0 && targetHeadcount >= 80) fit = "best";
    else if (idx === 0 && targetHeadcount < 80) fit = "large";
    else if (idx >= 3 && targetHeadcount >= 150) fit = "small";
    else if (idx === 1 && targetHeadcount >= 50 && targetHeadcount < 150) fit = "best";

    return { ...h, scaledPrice, fit };
  });
}